project:
  type: website

website:
  site-url: https://iqb-vocabs.github.io/p53/
  favicon: favicon.ico
  page-navigation: true
  repo-url: https://github.com/iqb-vocabs/p53/
  navbar:
    logo: IQB-klein.png
    search: true
    left:
      - href: index.qmd
        text: "Metadatenprofile für Testaufgaben: Englisch Sek I"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
