project:
  type: website

website:
  site-url: https://iqb-vocabs.github.io/p53/
  title: "Metadatenprofil"
  favicon: favicon.ico
  page-navigation: true
  repo-url: https://github.com/iqb-vocabs/p53/
  page-footer:
    background: light
    right:
      - text: "IQB 2024"
        href: https://www.iqb.hu-berlin.de
    left:
      - icon: IQB-klein.png
        href: index.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    anchor-sections: true
    link-external-icon: true
    link-external-newwindow: true
