on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master

name: Create new qmd-page

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Create new branch
        run: |
              git config --global user.email "yanpingchenlin@gmail.com"
              git config --global user.name "nanoyan"
              git checkout -b gh-prepare
              npm ci
              npm run validate_q
              git add -A
              git commit -m 'Create new index.qmd'
              git push --set-upstream origin gh-prepare --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
